
//CurrentWorkout Modals
export const SET_EXERCISE_VISIBILITY = "SET_EXERCISE_VISIBILITY";
export const SET_ADD_WEIGHT_MODAL_VISIBILITY =
  "SET_ADD_WEIGHT_MODAL_VISIBILITY";
export const SET_EDIT_WEIGHT_REPS_MODAL_VISIBILITY =
  "SET_EDIT_WEIGHT_REPS_MODAL_VISIBILITY";

export const ADD_EXERCISE = "ADD_EXERCISE";
export const ADD_EXERCISE_TO_SECTIONLIST = "ADD_EXERCISE_TO_SECTIONLIST";
export const DELETE_EXERCISE_FROM_SECTIONLIST =
  "DELETE_EXERCISE_FROM_SECTIONLIST";
export const CLEAR_CURRENT_WORKOUT = "CLEAR_CURRENT_WORKOUT";
export const UPDATE_EMPTY = "UPDATE_EMPTY";
export const ADD_DATE = "ADD_DATE";
export const SET_CURRENT_DATE = "SET_CURRENT_DATE";
export const ADD_MARKED_DATE = "ADD_MARKED_DATE";

export const UPDATE_WEIGHT_DATA = "UPDATE_WEIGHT_DATA";
export const UPDATE_BFR_DATA = "UPDATE_BFR_DATA";

export const ADD_NEW_EXERCISE_LIST = "ADD_NEW_EXERCISE_LIST";
export const ADD_WEIGHT_TO_EXERCISE = "ADD_WEIGHT_TO_EXERCISE";
export const EDIT_WEIGHT_REPS_IN_EXERCISE = "EDIT_WEIGHT_REPS_IN_EXERCISE";
export const DELETE_EXERCISE_FROM_WORKOUTLIST =
  "DELETE_EXERCISE_FROM_WORKOUTLIST";
//
export const UPDATE_EXERCISE_SCORE = "UPDATE_EXERCISE_SCORE";


//Calendar
export const ADD_HISTORY_MARKED_DATE = "ADD_HISTORY_MARKED_DATE";

export const SET_EDIT_HISTORY_EXERCISE_MODAL_VISIBILITY =
  "SET_EDIT_HISTORY_EXERCISE_MODAL_VISIBILITY";
export const SET_CALENDAR_EDIT_HISTORY_ADD_WEIGHT_MODAL_VISIBILITY =
  "SET_CALENDAR_EDIT_HISTORY_ADD_WEIGHT_MODAL_VISIBILITY";
export const SET_CALENDAR_EDIT_HISTORY_EDIT_WEIGHT_REPS_MODAL_VISIBILITY =
  "SET_CALENDAR_EDIT_HISTORY_EDIT_WEIGHT_REPS_MODAL_VISIBILITY";
export const CHANGE_CHECK_BUTTON_AVAILABILITY_IN_EDIT_HISTORY =
  "CHANGE_CHECK_BUTTON_AVAILABILITY_IN_EDIT_HISTORY";

export const ADD_WEIGHT_REPS_TO_EXERCISE_IN_CALENDAR_HISTORY =
  "ADD_WEIGHT_REPS_TO_EXERCISE_IN_CALENDAR_HISTORY";
export const EDIT_WEIGHT_REPS_IN_WORKOUT_OF_CALENDAR_HISTORY_ACTION =
  "EDIT_WEIGHT_REPS_IN_WORKOUT_OF_CALENDAR_HISTORY_ACTION";

export const ADD_EXERCISES_TO_EXERCISE_LIST_OF_WORKOUT_HISTORY =
  "ADD_EXERCISES_TO_EXERCISE_LIST_OF_WORKOUT_HISTORY";
export const DELETE_EXERCISES_FROM_EXERCISE_LIST_OF_WORKOUT_HISTORY =
  "DELETE_EXERCISES_FROM_EXERCISE_LIST_OF_WORKOUT_HISTORY";
export const ADD_EXERCISES_LIST_TO_WORKOUT_HISTORY =
  "ADD_EXERCISES_LIST_TO_WORKOUT_HISTORY";

export const SET_REMINDER_MODAL_IN_EDIT_HISTORY =
  "SET_REMINDER_MODAL_IN_EDIT_HISTORY";

//Set notifications

export const SET_NOTIFICATION_MODAL_VISIBILITY =
  "SET_NOTIFICATION_MODAL_VISIBILITY";

export const CHOOSE_DAY_IN_WEEK = "CHOOSE_DAY_IN_WEEK";

// Ken's custom actions
export const ADD_WORKOUTS_TO_DATE =
  "ADD_WORKOUTS_TO_DATE";

export const DELETE_WORKOUTS_FROM_DATE =
  "DELETE_WORKOUTS_FROM_DATE";